#
# MAINTAINER        Carson,C.J.Zeong <zcy@nicescale.com>
# DOCKER-VERSION    1.6.2
#
# Dockerizing HelloWorld: Dockerfile for building HelloWorld images
#
FROM       daiyan/tomcat:1.7
MAINTAINER Carson,C.J.Zeong <zcy@nicescale.com>

